// named.conf (BIND9)
//
acl labnet {
  127.0.0.1;      //localhost
  172.31.27.0/24; //localnet (corp.net.)
};

//
options {
  directory "/var/named";
  version "FLAG{hax3rs_l0ve_vers1on_number5!}";

  recursion yes;
  empty-zones-enable no;

  allow-query       { labnet; };
  allow-query-cache { labnet; };
  allow-recursion   { labnet; };
  allow-transfer    { labnet; }; //vulnerability

  dnssec-validation no;

  auth-nxdomain no;
  listen-on port 53 { 127.0.0.1; 172.31.27.201; };
  listen-on-v6 { none; };

  forwarders { 172.31.1.201; };
};

// FORWARD ZONE FOR corp.net.
zone "corp.net." {
  type master;
  file "corp.net.db";
};

// REVERSE ZONE FOR corp.net.
zone "27.31.172.in-addr.arpa." {
  type master;
  file "corp.net.rev";
};
